Homework1
made-ml-in-prod-2021/sergey-msu pull request #3
Opened 2021-04-26 11:03 UTC by sergey-msu

Все сделано в соответствии с заданием. <br>
**Основные моменты:**

1. В решении имплементирован пайплайн обучения для рекомендованного датасета https://www.kaggle.com/ronitf/heart-disease-uci. Структуру проекта взял в основном из https://drivendata.github.io/cookiecutter-data-science/, неиспользуемые папки почистил, кое-что поменял.

2. Имплементировал полное конфигурирование приложения из иерархически структурированных конфигов (папка configs/). Для конфигурации приложения из файлов конфигов использовал hydra. Имплементированы модели - логрегрессия и лес.   Запуск пайплайна тренировки из терминала для логрегрессии:
    

        python train_pipeline.py train=random_forest

для леса:

    python train_pipeline.py train=random_forest

3. Для добавления новой модели достаточно просто добавить новый конфиг в папку configs/train с ее обучаемыми параметрами. Для моделей, имеющих стандартный интерфейсfit/predict, кода писать вообще не нужно - класс модели создается рефлексией через locate(). Далее можно запускать также из терминала:

        python train_pipeline.py train=my_new_model
4. Сама тренировка реализована как grid-search по диапазонам параметров, которые явно указываются в конфигах. 

5. Predict тоже реализован как пайплайн - аналогично train_pipeline. Полностью конфигурируется гидрой из файлов конфигов. Берет на вход путь к файу обученной на трейне модели и делает предсказание, которое затем сохраняет в обозначенное в конфиге место: 

    python train_pipeline.py train=log_regression
    python test_pipeline.py

или

    python train_pipeline.py train=random_forest
    python test_pipeline.py

6. Для тестов сгенерировал приближенные к реальности рандомные, без использования сторонних библиотек. 

<br><br>
**Самооценка**: вроде бы имплементировано все, что указано в задании за исключением CI через git actions.
Если обнаруженные на ревью недостатки не окажутся критичными, надеюсь на оценку в районе макс_балл минус 3 балла за CI.

2021-05-07 20:05 UTC, Sergey-Pravdyukov commented
- EDA выглядит голословно. Между графиками стоит добавить markdown описание какие промежуточные выводы были получены из предыдущей ячейки и какие новые гипотезы исходя из этих выводов можно создать.
- Логировать стоит не только train_pipeline.py и predict_pipeline.py. Тренировка и предсказание лишь один небольшой этап пайплайна. Здорово когда логируются все этапы пайплайна, чтобы легко и быстро можно было отследить что и где поломалось, с какими параметрами запустилось и так далее.
- Общее замечание: при использовании структуры директориев отличной от cookiecutter имеет смысл коротко описать какой функционал выполняет модуль, который не генерится cookiecutter, а является кастомным. Это позволит сильно ускорить поиск нужного модуля, так как модуль пишется один раз, а читается много раз. Замечаение касается директории src/entities, например.

За вычетом этих недочетов получается 37 баллов.

В целом работа хорошая, молодец!

2021-05-07 20:06 UTC, Sergey-Pravdyukov approved these changes

2021-05-07 20:21 UTC, Sergey-Pravdyukov requested changes
- EDA выглядит голословно. Между графиками стоит добавить markdown описание какие промежуточные выводы были получены из предыдущей ячейки и какие новые гипотезы исходя из этих выводов можно создать.

- Логировать стоит не только train_pipeline.py и predict_pipeline.py. Тренировка и предсказание лишь один небольшой этап пайплайна. Здорово когда логируются все этапы пайплайна, чтобы легко и быстро можно было отследить что и где поломалось, с какими параметрами запустилось и так далее.

- Общее замечание: при использовании структуры директориев отличной от cookiecutter имеет смысл коротко описать какой функционал выполняет модуль, который не генерится cookiecutter, а является кастомным. Это позволит сильно ускорить поиск нужного модуля, так как модуль пишется один раз, а читается много раз. Замечаение касается директории src/entities, например.

Тем не менее работа классная, 32 балла. Молодец!

2021-05-07 20:37 UTC, sergey-msu commented
> * EDA выглядит голословно. Между графиками стоит добавить markdown описание какие промежуточные выводы были получены из предыдущей ячейки и какие новые гипотезы исходя из этих выводов можно создать. За пункт 1) снимаю один балл.
> * Логировать стоит не только train_pipeline.py и predict_pipeline.py. Тренировка и предсказание лишь один небольшой этап пайплайна. Здорово когда логируются все этапы пайплайна, чтобы легко и быстро можно было отследить что и где поломалось, с какими параметрами запустилось и так далее. За пункт 3) снимаю один балл.
> * Общее замечание: при использовании структуры директориев отличной от cookiecutter имеет смысл коротко описать какой функционал выполняет модуль, который не генерится cookiecutter, а является кастомным. Это позволит сильно ускорить поиск нужного модуля, так как модуль пишется один раз, а читается много раз. Замечаение касается директории src/entities, например. За пункт 0) снимаю один балл.
> 
> Тем не менее работа классная, 32 балла. Молодец!

Спасибо за ревью!

1. EDA специально сделал простым, так как задача была игрушечная, соответственно мне показалось, что задание не совсем в том, чтобы сделать реальное EDA для датасета типа титаника.
2. Логер обычно протягиваю в конструктор всех классов, это можно безусловно легко сделать и здесь. Можно без проблем допротягивать их везде.
3. Все __init__ файлы пакетов вроде бы прокоментировал. В пакете entities тоже. Коментарии расставлены для каждого класса и каждого метода в расширенном виде - с описанием переменных. Требовалось что-то другое?

2021-05-08 09:46 UTC, Sergey-Pravdyukov commented
> > * EDA выглядит голословно. Между графиками стоит добавить markdown описание какие промежуточные выводы были получены из предыдущей ячейки и какие новые гипотезы исходя из этих выводов можно создать. За пункт 1) снимаю один балл.
> > * Логировать стоит не только train_pipeline.py и predict_pipeline.py. Тренировка и предсказание лишь один небольшой этап пайплайна. Здорово когда логируются все этапы пайплайна, чтобы легко и быстро можно было отследить что и где поломалось, с какими параметрами запустилось и так далее. За пункт 3) снимаю один балл.
> > * Общее замечание: при использовании структуры директориев отличной от cookiecutter имеет смысл коротко описать какой функционал выполняет модуль, который не генерится cookiecutter, а является кастомным. Это позволит сильно ускорить поиск нужного модуля, так как модуль пишется один раз, а читается много раз. Замечаение касается директории src/entities, например. За пункт 0) снимаю один балл.
> > 
> > Тем не менее работа классная, 32 балла. Молодец!
> 
> Спасибо за ревью!
> 
> 1. EDA специально сделал простым, так как задача была игрушечная, соответственно мне показалось, что задание не совсем в том, чтобы сделать реальное EDA для датасета типа титаника.
> 2. Логер обычно протягиваю в конструктор всех классов, это можно безусловно легко сделать и здесь. Можно без проблем допротягивать их везде.
> 3. Все **init** файлы пакетов вроде бы прокоментировал. В пакете entities тоже. Коментарии расставлены для каждого класса и каждого метода в расширенном виде - с описанием переменных. Требовалось что-то другое?

1. Кратенько опиши промежуточные выводы после графиков. EDA проведено, а как его интерпретировать и что из него извлечь непонятно.
2. Да, было бы логично увидеть логирование на всех этапах пайплайна.
3. Имел ввиду добавление короткого README.md для каждого кастомного пакета или модуля. То есть если добавить README.md для пакета, то для модулей внутри уже ненужно. Главное - верхнеуровневое описание, чтобы можно было легко навигироваться по директориям без заглядывания в код. Это полезно для быстрого знакомства с кодовой базой, человеку который видит твой код впервые.

2021-05-09 09:59 UTC, sergey-msu commented
> > > * EDA выглядит голословно. Между графиками стоит добавить markdown описание какие промежуточные выводы были получены из предыдущей ячейки и какие новые гипотезы исходя из этих выводов можно создать. За пункт 1) снимаю один балл.
> > > * Логировать стоит не только train_pipeline.py и predict_pipeline.py. Тренировка и предсказание лишь один небольшой этап пайплайна. Здорово когда логируются все этапы пайплайна, чтобы легко и быстро можно было отследить что и где поломалось, с какими параметрами запустилось и так далее. За пункт 3) снимаю один балл.
> > > * Общее замечание: при использовании структуры директориев отличной от cookiecutter имеет смысл коротко описать какой функционал выполняет модуль, который не генерится cookiecutter, а является кастомным. Это позволит сильно ускорить поиск нужного модуля, так как модуль пишется один раз, а читается много раз. Замечаение касается директории src/entities, например. За пункт 0) снимаю один балл.
> > > 
> > > Тем не менее работа классная, 32 балла. Молодец!
> > 
> > 
> > Спасибо за ревью!
> > 
> > 1. EDA специально сделал простым, так как задача была игрушечная, соответственно мне показалось, что задание не совсем в том, чтобы сделать реальное EDA для датасета типа титаника.
> > 2. Логер обычно протягиваю в конструктор всех классов, это можно безусловно легко сделать и здесь. Можно без проблем допротягивать их везде.
> > 3. Все **init** файлы пакетов вроде бы прокоментировал. В пакете entities тоже. Коментарии расставлены для каждого класса и каждого метода в расширенном виде - с описанием переменных. Требовалось что-то другое?
> 
> 1. Кратенько опиши промежуточные выводы после графиков. EDA проведено, а как его интерпретировать и что из него извлечь непонятно.
> 2. Да, было бы логично увидеть логирование на всех этапах пайплайна.
> 3. Имел ввиду добавление короткого README.md для каждого кастомного пакета или модуля. То есть если добавить README.md для пакета, то для модулей внутри уже ненужно. Главное - верхнеуровневое описание, чтобы можно было легко навигироваться по директориям без заглядывания в код. Это полезно для быстрого знакомства с кодовой базой, человеку который видит твой код впервые.

Спасибо за разъяснения! Стало понятнее

Поправил 
1. описал выводы EDA в ноутбуке и скрипте отчета
2. протянул логгер вглубь кастомных классов, логирую их методы внутри

Сделал github actions (этого не было).

но не стал добавлять readme на каждый модуль / пакет, так как это кажется странноватым. В корневом readme.md есть их описание. На Ваше усмотрение, конечно.

Еща раз спасибо за ревью

2021-05-10 12:34 UTC, Sergey-Pravdyukov approved these changes
Отличная работа! 38 баллов.

2021-05-11 07:13 UTC, sergey-msu commented
> Отличная работа! 38 баллов.

огромнейшее спасибо!!

2021-05-11 07:26 UTC, Sergey-Pravdyukov commented
@dertty, привет! 

Прошу предпринять шаги в соответствии с правилами ревью от Михаила: 

> Про ревью друг друга:
Когда вас добавили в ревью, посмотрите код коллеги, напишите свои замечания, если что-то по вашему мнению сделано не очень хорошо, что можно в этом коде улучшить, если видите особенно клевый участок кода, то можно похвалить автора=) И не стоит себя недооценивать! Далее напишите, какому кол-ву баллов по вашему мнению соотвествует работа и почему бы вы лично что-то сняли. 
 
Если вас назначили и вы НЕ БУДЕТЕ делать ревью, смотреть код принципиально, то удалите себя из ревьюеров и добавьте students заново(выберет другого)
 
Если решили покинуть курс(не сдавать домашние работы), то заполните форму, я удалю из организации и вы не будете попадать в ревьюеры. (не вводите ники друг друга, это жестко!)
 
Какая мотивация для вас так делать?
1) Фан
2) 2 балла за факт сделанного ревью и поставленной оценки
3) Каждый из преподавателей для каждого домашнего задания будут выбирать лучшего ревьюера и мы поставим ему не 2, а 7 баллов(не обязательно количество таких людей будет равно количеству преподавателей, но так как вас много -- это вполне возможно)

2021-05-11 07:37 UTC, merged