Homework3
made-ml-in-prod-2021/sergey-msu pull request #5
Opened 2021-05-28 09:51 UTC by sergey-msu

Реализовал все, кроме MLFlow.

Особенности решения:
- даги и таски конфигурируются из yaml файлов
- в таски протянул логер для более детального логирования бизнес-логики (игрушечной, но тем не менее)
- время запусков дагов подготовки данных и обучения/предсказания модели специально выставлены
одинаковыми, чтобы продемонстрировать действие сенсоров
- весь бизнес код в дагах максимально простой и демонстрационный - для демонстрации оркестрации, а не ML контента. 
- реализованы тесты на консистентность DAG-ов. 
- реализован алерт через google SMTP.
- не стал внедрять MLFlow.

Если мои подсчеты верны, то максимальный балл без MLFlow - 42, если ревью не выявит неисправимых критических ошибок)

<br>
<br>

**Все DAG-и:**
![all_dags](https://user-images.githubusercontent.com/12846614/119965065-8916f880-bfb2-11eb-9dd7-f7dad2b7f96c.png)
<br>

**DAG по сбору данных:**
![collect_data](https://user-images.githubusercontent.com/12846614/119965078-8caa7f80-bfb2-11eb-9a68-34ce30d23eec.png)
<br>

**DAG по обучению модели:**
![train_model](https://user-images.githubusercontent.com/12846614/119965097-9207ca00-bfb2-11eb-8aad-157a5d7c7944.png)
<br>

**DAG по инференсу:**
![predict_model](https://user-images.githubusercontent.com/12846614/119965108-946a2400-bfb2-11eb-8918-809ef9badd1d.png)

2021-05-30 12:30 UTC, kbrodt requested changes
По коду всё хорошо. Несколько замечаний:

1) обогатить ридми документацией. Что нужно сделать перед использованием, так как у меня не получилось поднять локально
2) общая проблема дублирования: конфиги, тесты и докер образы (слишком много жрёт диск)
3) как запустить тесты (хотя я спёр их у тебя и сам не знаю как их запустить ;0 )

2021-05-30 12:30 UTC, kbrodt commented on airflow_ml_dags/dags/predict_model.py
> +    wait_for_data >> data_prepare >> model_predict >> data_clean
нужно дождаться модель

2021-05-30 12:30 UTC, kbrodt commented on airflow_ml_dags/docker-compose.yml
> +  - AIRFLOW__SMTP__SMTP_USER=spmathf@gmail.com
вынести в переменную окружения как и пароль

2021-05-30 12:30 UTC, kbrodt commented on airflow_ml_dags/README.md
> +docker compose up
хотелось бы больше инфы про то, что нужно сделать перед запуском, как прогнать тесты

2021-05-30 12:30 UTC, kbrodt commented on airflow_ml_dags/tests/test_collect_data_dag.py
> +def dag_bag():
тесты однотипные, может быть параметризовать

2021-05-30 12:30 UTC, kbrodt commented on airflow_ml_dags/configs/collect_data.yaml
> +default_args:
конфиги похожие, может быть вынести в один базовый конфиг и его уже мёржить со специализированными

2021-05-30 12:30 UTC, kbrodt commented on .github/workflows/github-ci.yml
> +    branches: [ homework3 ]
можно ещё линтер и тесты прикрутить

2021-05-30 12:30 UTC, kbrodt commented on airflow_ml_dags/docker-compose.yml
> +  data_split:
кажется слишком жирно поднимать разные образы для таких задач, можно объединить несколько в один, иначе потребуется больше 10гб, только чтобы поднять

```
sergey.polyanskikh/airflow-model-predict    latest            a7e17911e25d   7 minutes ago   1.24GB
sergey.polyanskikh/airflow-model-validate   latest            fe1d97ac9e8c   7 minutes ago   1.24GB
sergey.polyanskikh/airflow-model-train      latest            1f03f048be6d   7 minutes ago   1.24GB
sergey.polyanskikh/airflow-data-split       latest            0fdab282f96b   7 minutes ago   1.24GB
sergey.polyanskikh/airflow-data-prepare     latest            ccb84e066d02   7 minutes ago   1.24GB
sergey.polyanskikh/airflow-data-clean       latest            5181ae2e9b9e   7 minutes ago   1.24GB
sergey.polyanskikh/airflow-data-merge       latest            5481e068538f   7 minutes ago   1.24GB
sergey.polyanskikh/airflow-data-download    latest            1d29b1c17755   7 minutes ago   1.24GB
sergey.polyanskikh/airflow-ml-base          latest            4c218c87775f   7 minutes ago   1.24GB
```

2021-05-30 12:38 UTC, kbrodt commented on airflow_ml_dags/docker-compose.yml
> +  data_split:
а, кажись я не прав и докер оптимизирует, переиспользует слои, поэтому диск так не забивается. Но всё же, хотелось бы объединить ;)

2021-05-30 12:53 UTC, Mikhail-M commented on airflow_ml_dags/docker-compose.yml
> +  data_split:
Ну не жирно=) 
Хороший нормальный способ, описан как один из доступных в ДЗ, это вкусовщина. 
Понятно, что в этой ситуации разбиение с такой гранулярностью скорее излишество, но это демонстрация паттерна, что эти штуки на самом деле могут быть очень независимы, на разных языках программирование и тд. и при этом работать жить вместе=)

2021-05-30 13:00 UTC, kbrodt commented on airflow_ml_dags/docker-compose.yml
> +  data_split:
тогда претензий про докер большей нет)

2021-05-30 15:20 UTC, sergey-msu commented on airflow_ml_dags/README.md
> +docker compose up
согласен, всегда лень маркап ридми заполнять)

2021-05-30 15:20 UTC, sergey-msu commented on airflow_ml_dags/dags/predict_model.py
> +    wait_for_data >> data_prepare >> model_predict >> data_clean
согласен, забыл

2021-05-30 15:22 UTC, sergey-msu commented on airflow_ml_dags/configs/collect_data.yaml
> +default_args:
да, но тут вечная проблема баланса как в наследовании ООП: отнаследуешься - все начинает зависеть от одного, не отнаследуешься - дублируешь. Конкретно в конфигах надо аккуратно, ибо потом страшно что-то в базе менять

2021-05-30 15:22 UTC, sergey-msu commented on .github/workflows/github-ci.yml
> +    branches: [ homework3 ]
тесты есть, линтер - да, стандарт)

2021-05-30 15:24 UTC, sergey-msu commented on airflow_ml_dags/docker-compose.yml
> +  data_split:
вот долго думал, в один это собирать контейнер или в разные, решил трактовать задание буквально :) - одна таска - один контейнер. Не всегда рационально, полностью согласен.

2021-05-30 15:30 UTC, kbrodt commented on airflow_ml_dags/configs/collect_data.yaml
> +default_args:
честно не знаю как лучше, я дилетант. У меня мания как можно меньше вводить мест для ввода параметров, которые зависят от пользователя

2021-05-30 15:31 UTC, kbrodt commented on .github/workflows/github-ci.yml
> +    branches: [ homework3 ]
тесты походу нужно мокать, потому что без поднятого окружения эирфло я не знаю как их запускать

2021-05-30 16:44 UTC, sergey-msu commented on airflow_ml_dags/dags/predict_model.py
> +    wait_for_data >> data_prepare >> model_predict >> data_clean
поправил

2021-05-30 16:46 UTC, sergey-msu commented on airflow_ml_dags/docker-compose.yml
> +  - AIRFLOW__SMTP__SMTP_USER=spmathf@gmail.com
поправил

2021-05-30 16:46 UTC, sergey-msu commented on airflow_ml_dags/tests/test_collect_data_dag.py
> +def dag_bag():
+

2021-05-30 17:39 UTC, kbrodt commented
Проект запускается локально, ответы принимаются и работа заслуживает свои баллы. По поводу общего конфига и параметризованных тестов, наверное, дело вкуса, у меня в этом опыта нет. Отдельный плюс за конфиги для дагов и логирование.

2021-05-30 17:40 UTC, kbrodt approved these changes

2021-06-01 09:30 UTC, Mikhail-M commented on airflow_ml_dags/docker-compose.yml
> +  data_split:
Одна таска один контейнер это в любом случае, а вот образ мог бы быть общим, ага

2021-06-01 10:22 UTC, sergey-msu commented on airflow_ml_dags/docker-compose.yml
> +  data_split:
да, согласен(

2021-06-02 16:22 UTC, sergey-msu commented on airflow_ml_dags/docker-compose.yml
> +  data_split:
> Одна таска -- один контейнер это в любом случае, а вот образ мог бы быть общим, ага

исправил

2021-06-06 10:14 UTC, Mikhail-M approved these changes
Баллы: 42
Сделано круто и что важно -- своевременно=)  
Доп лайк за конфиги.

2021-06-06 15:54 UTC, merged